// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace InsultGenerator
{
	public partial class PreferencesViewController : NSViewController
	{
		public PreferencesViewController(IntPtr handle) : base(handle)
		{
		}

		partial void TouchBarSwitchStateChanged(AppKit.NSSwitch sender)
		{
			if (TouchBarEnableSwitch.State == 0)
			{
				// NSTouchBar.
			} else
			{
				
			}
		}

		partial void AppearanceComboBoxChanged(AppKit.NSComboBox sender)
		{
			if (AppearanceComboBox.SelectedIndex == 0)
			{
				// NSApplication.SharedApplication.Appearance = NSAppearance.
			} else if (AppearanceComboBox.SelectedIndex == 1)
			{
				NSApplication.SharedApplication.Appearance = NSAppearance.GetAppearance(NSAppearance.NameAqua);
			} else if (AppearanceComboBox.SelectedIndex == 2)
			{
				NSApplication.SharedApplication.Appearance = NSAppearance.GetAppearance(NSAppearance.NameAqua);
			}

		}
	}
}
