// This file has been autogenerated from a class added in the UI designer.

using System;
using System.IO;
using System.Collections;
using Foundation;
using AppKit;

namespace InsultGenerator
{
	public partial class PreviousInsultsController : NSViewController
	{
		public bool ShowSaveAsSheet { get; set;} = true;
		private string _generatedInsultsString;
		
		public PreviousInsultsController(IntPtr handle) : base(handle)
		{
		}
		
        public void GetDataFromParent()
        {
            _generatedInsultsString = "";
            for (int i = 0; i < InsultViewController.GeneratedInsults.Count; i++)
            {
                _generatedInsultsString += InsultViewController.GeneratedInsults[i] + "\n\n";
            }
        }

        partial void SaveInsultsButtonClicked(NSButton sender)
        {
            ShowSaveAs(sender);
        }

        partial void ClearInsultsButtonClicked(AppKit.NSButton sender)
        {
            InsultViewController.GeneratedInsults.Clear();
            InsultsTextView.Value = string.Empty;
            NSApplication.SharedApplication.KeyWindow.Close();
        }
        
        [Export("saveDocumentAs:")]
        // ReSharper disable once UnusedParameter.Local
        void ShowSaveAs (NSObject sender)
        {
            NSWindow window = NSApplication.SharedApplication.KeyWindow;
            var dlg = new NSSavePanel ();
            dlg.Title = "Save Text File";
            dlg.AllowedFileTypes = new[] { "txt"};
            dlg.NameFieldStringValue = "insults.txt";

                dlg.BeginSheet(window,(result ) =>
                {
                    if (result == 0)
                    {
                        Console.WriteLine("Save unsuccessful. User probably cancelled the save or we were denied permission by macOS.");
                        SaveResultTextField.StringValue = "Save Unsuccessful. You probably clicked \"Cancel\".";
                    }
                    
                    else if (result == 1)
                    {

                        try
                        {
                            StreamWriter streamWriter = new StreamWriter(dlg.Filename);
                            streamWriter.Write(_generatedInsultsString);
                            streamWriter.Close();
                            SaveResultTextField.StringValue = "List successfully saved.";
                        }
                        catch (System.ArgumentNullException e)
                        {
                            var alert = new NSAlert()
                            {
                                AlertStyle = NSAlertStyle.Critical,
                                InformativeText = "Shit's fucked yo",
                                MessageText = "Boom",
                            };
                        }

                    }

                });
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            
            GetDataFromParent();

            InsultsTextView.Value = _generatedInsultsString;
        }
	}
}
