// This file has been autogenerated from a class added in the UI designer.

using System;
using System.IO;
using System.Collections;
using Foundation;
using AppKit;

namespace InsultGenerator
{
	public partial class PreviousInsultsController : NSViewController
	{
		public bool ShowSaveAsSheet { get; set;} = true;
		private string _generatedInsultsString;
		
		public PreviousInsultsController(IntPtr handle) : base(handle)
		{
		}
		
        public void GetDataFromParent()
        {
            _generatedInsultsString = "";
            for (int i = 0; i < InsultViewController.GeneratedInsults.Count; i++)
            {
                _generatedInsultsString += InsultViewController.GeneratedInsults[i] + "\n\n";
            }
        }

        partial void SaveInsultsButtonClicked(NSButton sender)
        {
            ShowSaveAs(sender);
        }

        partial void ClearInsultsButtonClicked(AppKit.NSButton sender)
        {
            InsultViewController.GeneratedInsults.Clear();
            InsultsTextView.Value = string.Empty;
            NSApplication.SharedApplication.KeyWindow.Close();
        }
        
        [Export("saveDocumentAs:")]
        // ReSharper disable once UnusedParameter.Local
        void ShowSaveAs (NSObject sender)
        {
            NSWindow window = NSApplication.SharedApplication.KeyWindow;
            var dlg = new NSSavePanel ();
            dlg.Title = "Save Text File";
            dlg.AllowedFileTypes = new[] { "txt"};
            dlg.NameFieldStringValue = "insults.txt";

                dlg.BeginSheet(window,(result ) =>
                {
                    if (result == 0)
                    {
                        return;
                    }
                    
                    else if (result == 1)
                    {
                        try
                        {
                            StreamWriter streamWriter = new StreamWriter(dlg.Url.Path);
                            streamWriter.Write(_generatedInsultsString);
                            streamWriter.Close();
                        }
                        catch (System.UnauthorizedAccessException e)
                        {
                            var alert = new NSAlert() {
                                AlertStyle = NSAlertStyle.Warning,
                                InformativeText =
                                    "We can't save here because you've denied us access. Please check Security & Privacy, then Files and Folders in System Preferences",
                                MessageText = "Access Denied",
                            };

                            alert.RunModal();

                        }

                    }

                });
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            
            GetDataFromParent();

            InsultsTextView.Value = _generatedInsultsString;
        }
	}
}
