// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections;
using Foundation;
using AppKit;

namespace InsultGenerator
{
    public partial class PreviousInsultsViewController : NSViewController
    {
        public bool ShowSaveAsSheet { get; set;} = true;
        private string _generatedInsultsString;

        public PreviousInsultsViewController(IntPtr handle) : base(handle)
        {
			
        }

        public void GetDataFromParent()
        {
            ArrayList generatedInsults = InsultViewController.GeneratedInsults;
            _generatedInsultsString = "";
            for (int i = 0; i < generatedInsults.Count; i++)
            {
                _generatedInsultsString += generatedInsults[i];
            }
        }

        // partial void SaveButtonPressed(AppKit.NSButton sender)
        // {
        //     var
        // }
        //
        // [Export("saveDocumentAs:")]
        // void ShowSaveAs (NSObject sender)
        // {
        //     var dlg = new NSSavePanel ();
        //     dlg.Title = "Save Text File";
        //     dlg.AllowedFileTypes = new string[] { "txt", "html", "md", "css" };
        //
        //     if (ShowSaveAsSheet) {
        //         dlg.BeginSheet(mainWindowController.Window,(result) => {
        //             var alert = new NSAlert () {
        //                 AlertStyle = NSAlertStyle.Critical,
        //                 InformativeText = "We need to save the document here...",
        //                 MessageText = "Save Document",
        //             };
        //             alert.RunModal ();
        //         });
        //     } else {
        //         if (dlg.RunModal () == 1) {
        //             var alert = new NSAlert () {
        //                 AlertStyle = NSAlertStyle.Critical,
        //                 InformativeText = "We need to save the document here...",
        //                 MessageText = "Save Document",
        //             };
        //             alert.RunModal ();
        //         }
        //     }
        //
        // }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            
            GetDataFromParent();
            
            
        }
    }
}