// This file has been autogenerated from a class added in the UI designer.

using System;
using AppKit;

namespace InsultGenerator
{
    public partial class ViewController : NSViewController
    {
        public ViewController(IntPtr handle) : base(handle)
        {
        }

        partial void GenerateInsultButtonPressed(NSButton sender)
        {
            var storyboard = NSStoryboard.FromName("Main", null);

            if (storyboard.InstantiateControllerWithIdentifier("GeneratedInsultController") is NSWindowController controller) controller.ShowWindow(sender: sender);
        }
    }
}